-- DropForeignKey
ALTER TABLE "mediciones" DROP CONSTRAINT IF EXISTS "mediciones_id_coleccion_fkey";

-- DropForeignKey
ALTER TABLE "mediciones" DROP CONSTRAINT IF EXISTS "mediciones_id_libreria_fkey";

-- AlterTable
ALTER TABLE "mediciones" DROP COLUMN IF EXISTS "id_coleccion",
DROP COLUMN IF EXISTS "id_libreria",
ADD COLUMN IF NOT EXISTS "Density" DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS "LRV" DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS "X" DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS "Y" DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS "Z" DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS "cmykC" DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS "cmykK" DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS "cmykM" DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS "cmykY" DOUBLE PRECISION;
